USE LIBRARY
set DATEFORMAT dmy

DROP TABLE IF EXISTS BOOK_CREATORS;
DROP TABLE IF EXISTS BOOK_EDITORS;
DROP TABLE IF EXISTS BOOK_TOPIC;
DROP TABLE IF EXISTS CREATOR;
DROP TABLE IF EXISTS PROFESSION;
DROP TABLE IF EXISTS TOPIC;
DROP TABLE IF EXISTS DEAL;
DROP TABLE IF EXISTS READER;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS EDITION;
DROP TABLE IF EXISTS SERIES;
DROP TABLE IF EXISTS PUBLISHING_COMPANY;
DROP TABLE IF EXISTS TYPE;
DROP TABLE IF EXISTS BOOK_TITLE;
DROP TABLE IF EXISTS ORIGINAL_BOOK;
DROP TABLE IF EXISTS LANGUAGE;


CREATE TABLE READER (
	reader_id SMALLINT IDENTITY PRIMARY KEY,
	last_name VARCHAR(15),
	first_name VARCHAR(15),
	patronym VARCHAR(15),
	email VARCHAR(30),
	phone_number CHAR(12) CHECK (phone_number LIKE('+[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')),
	passport CHAR(10) CHECK (passport LIKE('[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')));

CREATE TABLE DEAL (
	deal_id SMALLINT IDENTITY PRIMARY KEY,
	reader_id SMALLINT,
	book_id SMALLINT,
	lending_date DATE,
	returning_date DATE,
	day_x_date AS DATEADD(day, 14, lending_date) );


CREATE TABLE BOOK (
	book_id SMALLINT IDENTITY PRIMARY KEY,
	edition_id SMALLINT,
	location_id SMALLINT );

CREATE TABLE LOCATION (
	location_id SMALLINT IDENTITY PRIMARY KEY,
	room_number SMALLINT,
	rack_number SMALLINT,
	shelf_number SMALLINT );

CREATE TABLE EDITION (
	edition_id SMALLINT IDENTITY PRIMARY KEY,
	series_id SMALLINT,
	publishing_company_id SMALLINT,
	type_id SMALLINT,
	book_title_id SMALLINT,
	volume_number TINYINT DEFAULT 1,
	periodicity SMALLINT,
	publishing_date DATE );

CREATE TABLE SERIES (
	series_id SMALLINT IDENTITY PRIMARY KEY,
	name VARCHAR(100) );

CREATE TABLE PUBLISHING_COMPANY (
	publishing_company_id SMALLINT IDENTITY PRIMARY KEY,
	name VARCHAR(30) );

CREATE TABLE TYPE (
	type_id SMALLINT IDENTITY PRIMARY KEY,
	name VARCHAR(30) );

CREATE TABLE BOOK_TITLE (
	book_title_id SMALLINT IDENTITY PRIMARY KEY,
	name VARCHAR(500),
	language_id TINYINT,
	original_book_id SMALLINT);

CREATE TABLE ORIGINAL_BOOK (
	original_book_id SMALLINT IDENTITY PRIMARY KEY,
	language_id TINYINT );

CREATE TABLE PROFESSION (
	profession_id SMALLINT IDENTITY PRIMARY KEY,
	name VARCHAR(15) );

CREATE TABLE BOOK_EDITORS (
	profession_id SMALLINT,
	edition_id SMALLINT,
	editor_id SMALLINT );

CREATE TABLE BOOK_CREATORS (
	profession_id SMALLINT,
	original_book_id SMALLINT,
	creator_id SMALLINT );

CREATE TABLE CREATOR (
	creator_id SMALLINT IDENTITY PRIMARY KEY,
	name VARCHAR(100) );

CREATE TABLE BOOK_TOPIC (
	original_book_id SMALLINT,
	topic_id SMALLINT );

CREATE TABLE TOPIC (
	topic_id SMALLINT IDENTITY PRIMARY KEY,
	name VARCHAR(30),
	overtopic_id SMALLINT );

CREATE TABLE LANGUAGE (
	language_id TINYINT IDENTITY PRIMARY KEY,
	language VARCHAR(15) );

ALTER TABLE DEAL
	ADD CONSTRAINT FK_Deal_Reader FOREIGN KEY (reader_id)
	REFERENCES READER (reader_id)
	ON UPDATE CASCADE
;

ALTER TABLE DEAL
	ADD CONSTRAINT FK_Deal_Book FOREIGN KEY (book_id)
	REFERENCES BOOK (book_id)
	ON UPDATE CASCADE
;

ALTER TABLE BOOK
   ADD CONSTRAINT FK_Book_Location FOREIGN KEY (location_id)
      REFERENCES LOCATION (location_id)
      ON UPDATE CASCADE
;

ALTER TABLE BOOK
   ADD CONSTRAINT FK_Book_Edition FOREIGN KEY (edition_id)
      REFERENCES EDITION (edition_id)
      ON UPDATE CASCADE
;

ALTER TABLE EDITION
   ADD CONSTRAINT FK_Edition_Series FOREIGN KEY (series_id)
      REFERENCES SERIES (series_id)
      ON UPDATE CASCADE
;

ALTER TABLE EDITION
   ADD CONSTRAINT FK_Edition_PublishingCompany FOREIGN KEY (publishing_company_id)
      REFERENCES PUBLISHING_COMPANY (publishing_company_id)
      ON UPDATE CASCADE
;

ALTER TABLE EDITION
   ADD CONSTRAINT FK_Edition_Type FOREIGN KEY (type_id)
      REFERENCES TYPE (type_id)
      ON UPDATE CASCADE
;

ALTER TABLE EDITION
   ADD CONSTRAINT FK_Edition_BookTitle FOREIGN KEY (book_title_id)
      REFERENCES BOOK_TITLE (book_title_id)
      ON UPDATE CASCADE
;


ALTER TABLE BOOK_TITLE
   ADD CONSTRAINT FK_BookTitle_Language FOREIGN KEY (language_id)
      REFERENCES LANGUAGE (language_id)
      ON UPDATE CASCADE
;

ALTER TABLE BOOK_TITLE
   ADD CONSTRAINT FK_BookTitle_OriginalBook FOREIGN KEY (original_book_id)
      REFERENCES ORIGINAL_BOOK (original_book_id)
      ON UPDATE CASCADE
;
ALTER TABLE BOOK_TOPIC
   ADD CONSTRAINT FK_BookTopic_OriginalBook FOREIGN KEY (original_book_id)
      REFERENCES ORIGINAL_BOOK (original_book_id)
      ON UPDATE CASCADE
;
ALTER TABLE BOOK_TOPIC
   ADD CONSTRAINT FK_BookTopic_Topic FOREIGN KEY (topic_id)
      REFERENCES TOPIC (topic_id)
      ON UPDATE CASCADE
;

ALTER TABLE TOPIC
   ADD CONSTRAINT FK_Topic_Overtopic FOREIGN KEY (overtopic_id)
      REFERENCES TOPIC (topic_id)
	  ON DELETE NO ACTION 
	  ON UPDATE NO ACTION
;

ALTER TABLE BOOK_EDITORS
   ADD CONSTRAINT FK_BookEditors_Edition FOREIGN KEY (edition_id)
      REFERENCES EDITION (edition_id)
      ON UPDATE CASCADE
;

ALTER TABLE BOOK_EDITORS
   ADD CONSTRAINT FK_BookEditors_Creator FOREIGN KEY (editor_id)
      REFERENCES CREATOR (creator_id)
      ON UPDATE CASCADE
;

ALTER TABLE BOOK_EDITORS
   ADD CONSTRAINT FK_BookEditors_Profession FOREIGN KEY (profession_id)
      REFERENCES PROFESSION (profession_id)
      ON UPDATE CASCADE
;

ALTER TABLE BOOK_CREATORS
   ADD CONSTRAINT FK_BookCreators_OriginalBook FOREIGN KEY (original_book_id)
      REFERENCES ORIGINAL_BOOK (original_book_id)
      ON UPDATE CASCADE
;

ALTER TABLE BOOK_CREATORS
   ADD CONSTRAINT FK_BookCreators_Creator FOREIGN KEY (creator_id)
      REFERENCES CREATOR (creator_id)
      ON UPDATE CASCADE
;

ALTER TABLE BOOK_CREATORS
   ADD CONSTRAINT FK_BookCreators_Profession FOREIGN KEY (profession_id)
      REFERENCES PROFESSION (profession_id)
      ON UPDATE CASCADE
;


INSERT INTO LANGUAGE VALUES('русский');
INSERT INTO LANGUAGE VALUES('английский');
INSERT INTO LANGUAGE VALUES('японский');
INSERT INTO LANGUAGE VALUES('французский');
INSERT INTO LANGUAGE VALUES('испанский');
INSERT INTO LANGUAGE VALUES('немецкий');

INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(1);
INSERT INTO ORIGINAL_BOOK VALUES(1);
INSERT INTO ORIGINAL_BOOK VALUES(1);
INSERT INTO ORIGINAL_BOOK VALUES(1);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(1);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(1);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(3);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);
INSERT INTO ORIGINAL_BOOK VALUES(2);

INSERT INTO BOOK_TITLE VALUES('КЭД - странная теория света и вещества', 1, 1);
INSERT INTO BOOK_TITLE VALUES('Непобедимое Солнце', 1, 2)
INSERT INTO BOOK_TITLE VALUES('Защита от темных искусств', 1, 3)
INSERT INTO BOOK_TITLE VALUES('Омерзительное искусство. Юмор и хоррор шедевров живописи', 1, 4)
INSERT INTO BOOK_TITLE VALUES('Основы каллиграфии и леттеринга. Прописи', 1, 5)
INSERT INTO BOOK_TITLE VALUES('Продавец обуви. История компании Nike, рассказанная ее основателем', 1, 6)
INSERT INTO BOOK_TITLE VALUES('Что скрывает кожа. 2 квадратных метра, которые диктуют, как нам жить', 1, 7)
INSERT INTO BOOK_TITLE VALUES('Уникальный экземпляр. Истории о том о сём', 1, 8)
INSERT INTO BOOK_TITLE VALUES('Макияж', 1, 9)
INSERT INTO BOOK_TITLE VALUES('Маленькая жизнь', 1, 10)
INSERT INTO BOOK_TITLE VALUES('TED Talks. Слова меняют мир. Первое официальное руководство по публичным выступлениям', 1, 11)
INSERT INTO BOOK_TITLE VALUES('Скажи «НЕТ» пластику: 101 способ использовать меньше пластика и спасти мир', 1, 12)
INSERT INTO BOOK_TITLE VALUES('Sapiens', 1, 13)
INSERT INTO BOOK_TITLE VALUES('Думай медленно... решай быстро', 1, 14)
INSERT INTO BOOK_TITLE VALUES('Магия утра. Как первый час дня определяет ваш успех', 1, 15)
INSERT INTO BOOK_TITLE VALUES('Важные годы. Почему не стоит откладывать жизнь на потом', 1, 16)
INSERT INTO BOOK_TITLE VALUES('Магическая уборка. Японское искусство наведения порядка дома и в жизни', 1, 17)
INSERT INTO BOOK_TITLE VALUES('Сила подсознания, или Как изменить жизнь за 4 недели', 1, 18)
INSERT INTO BOOK_TITLE VALUES('Не ной. Только тот, кто перестал сетовать на судьбу, может стать богатым', 1, 19)
INSERT INTO BOOK_TITLE VALUES('Тук-тук, сердце! Как подружиться с самым неутомимым органом и что будет, если этого не сделать', 1, 20)


INSERT INTO TYPE VALUES('мягкая обложка');
INSERT INTO TYPE VALUES('твёрдая обложка');
INSERT INTO TYPE VALUES('суперобложка');

INSERT INTO PUBLISHING_COMPANY VALUES('АСТ');
INSERT INTO PUBLISHING_COMPANY VALUES('Эксмо');
INSERT INTO PUBLISHING_COMPANY VALUES('Манн Иванов и Фербер');
INSERT INTO PUBLISHING_COMPANY VALUES('Азбука');
INSERT INTO PUBLISHING_COMPANY VALUES('Одри');
INSERT INTO PUBLISHING_COMPANY VALUES('Corpus');
INSERT INTO PUBLISHING_COMPANY VALUES('Синдбад');

INSERT INTO SERIES VALUES('Эксклюзивная классика');
INSERT INTO SERIES VALUES('Единственный и неповторимый. Виктор Пелевин');
INSERT INTO SERIES VALUES('Библиотека фонда «Эволюция»');
INSERT INTO SERIES VALUES('Искусство с блогерами');
INSERT INTO SERIES VALUES('Бизнес. Pocket');
INSERT INTO SERIES VALUES('Сенсация в медицине');
INSERT INTO SERIES VALUES('Азбука-бестселлер');
INSERT INTO SERIES VALUES('Елена Крыгина представляет. Рекомендации топ-визажиста');
INSERT INTO SERIES VALUES('Corpus.[roman]');
INSERT INTO SERIES VALUES('Психология влияния');
INSERT INTO SERIES VALUES('Подарочные издания. Досуг');
INSERT INTO SERIES VALUES('Думай и решай');
INSERT INTO SERIES VALUES('МИФ. Личное развитие');
INSERT INTO SERIES VALUES('Метод Кон Мари');
INSERT INTO SERIES VALUES('Психология. Кроличья нора');
INSERT INTO SERIES VALUES('Книги до 35 лет');

INSERT INTO EDITION VALUES(1, 1, 1, 1, 1, NULL, '01-01-2018');
INSERT INTO EDITION VALUES(2, 2, 2, 2, 1, NULL, '01-01-2020');
INSERT INTO EDITION VALUES(3, 1, 2, 3, 1, NULL, '01-01-2018');
INSERT INTO EDITION VALUES(4, 2, 2, 4, 1, NULL, '01-01-2018');
INSERT INTO EDITION VALUES(NULL, 3, 2, 5, 1, NULL, '01-01-2017');
INSERT INTO EDITION VALUES(5, 2, 1, 6, 1,  NULL, '01-01-2017');
INSERT INTO EDITION VALUES(6, 2, 2, 7, 1, NULL, '01-01-2017');
INSERT INTO EDITION VALUES(7, 4, 3, 8, 1, NULL, '01-01-2017');
INSERT INTO EDITION VALUES(8, 5, 2, 9, 1, NULL, '01-01-2017');
INSERT INTO EDITION VALUES(9, 6, 2, 10, 1, NULL, '01-01-2016');
INSERT INTO EDITION VALUES(10, 2, 2, 11, 1, NULL, '01-01-2016');
INSERT INTO EDITION VALUES(11, 2, 1, 12, 1, NULL, '01-01-2019');
INSERT INTO EDITION VALUES(NULL, 7, 2, 13, 1, NULL, '01-01-2016');
INSERT INTO EDITION VALUES(12, 1, 2, 14, 1, NULL, '01-01-2017');
INSERT INTO EDITION VALUES(NULL, 3, 2, 15, 1, NULL, '01-01-2016');
INSERT INTO EDITION VALUES(13, 3, 2, 16, 1, NULL, '01-01-2016');
INSERT INTO EDITION VALUES(14, 2, 2, 17, 1, NULL, '01-01-2015');
INSERT INTO EDITION VALUES(15, 2, 2, 18, 1, NULL, '01-01-2013');
INSERT INTO EDITION VALUES(16, 2, 2, 19, 1, NULL, '01-01-2019');
INSERT INTO EDITION VALUES(6, 2, 2, 20, 1, NULL, '01-01-2016');

INSERT INTO LOCATION VALUES(1, 1, 1);
INSERT INTO LOCATION VALUES(1, 1, 2);
INSERT INTO LOCATION VALUES(1, 2, 1);
INSERT INTO LOCATION VALUES(1, 2, 2);
INSERT INTO LOCATION VALUES(1, 3, 1);
INSERT INTO LOCATION VALUES(1, 3, 2);
INSERT INTO LOCATION VALUES(1, 4, 1);
INSERT INTO LOCATION VALUES(1, 4, 2);

INSERT INTO BOOK VALUES(1, 1);
INSERT INTO BOOK VALUES(2, 1);
INSERT INTO BOOK VALUES(3, 1);
INSERT INTO BOOK VALUES(4, 1);
INSERT INTO BOOK VALUES(5, 1);
INSERT INTO BOOK VALUES(6, 1);
INSERT INTO BOOK VALUES(7, 1);
INSERT INTO BOOK VALUES(8, 1);
INSERT INTO BOOK VALUES(9, 1);
INSERT INTO BOOK VALUES(10, 1);
INSERT INTO BOOK VALUES(11, 2);
INSERT INTO BOOK VALUES(12, 2);
INSERT INTO BOOK VALUES(13, 2);
INSERT INTO BOOK VALUES(14, 2);
INSERT INTO BOOK VALUES(15, 2);
INSERT INTO BOOK VALUES(16, 2);
INSERT INTO BOOK VALUES(17, 2);
INSERT INTO BOOK VALUES(18, 2);
INSERT INTO BOOK VALUES(19, 2);
INSERT INTO BOOK VALUES(20, 2);

INSERT INTO READER VALUES('Антипова', 'Наталья', 'Кирилловна', 'ank@phystech.edu', '+79000000000', '3315100000');
INSERT INTO READER VALUES('Ачарйа', 'Кирилл', 'Кишорович', 'akk@phystech.edu', '+79000000001', '3315100001');
INSERT INTO READER VALUES('Барышева', 'Анастасия', 'Николаевна', 'ban@phystech.edu', '+79000000002', '3315123456');
INSERT INTO READER VALUES('Богданов', 'Александр', 'Иванович', 'bai@phystech.edu', '+79000000003', '3315100003');
INSERT INTO READER VALUES('Буняков', 'Михаил', 'Константинович', 'bmk@phystech.edu', '+79000000004', '3315100004');
INSERT INTO READER VALUES('Гайфутдинов', 'Дамир', 'Вильдарович', 'gdv@phystech.edu', '+79000000005', '3315100005');
INSERT INTO READER VALUES('Исмаилов', 'Исмаил', 'Арсенович', 'iia@phystech.edu', '+79000000006', '3315100006');
INSERT INTO READER VALUES('Кузнецова', 'Алина', 'Петровна', 'kap@phystech.edu', '+79000000007', '3315100007');
INSERT INTO READER VALUES('Романов', 'Михаил', 'Владиславович', 'rmv@phystech.edu', '+79000000008', '3315100008');
INSERT INTO READER VALUES('Сысоев', 'Ярослав', 'Игоревич', 'syai@phystech.edu', '+79000000009', '3315100009');
INSERT INTO READER VALUES('Тихомиров', 'Андрей', 'Дмитриевич', 'tad@phystech.edu', '+79000000010', '3315100010');
INSERT INTO READER VALUES('Хайдапов', 'Жамсо', 'Бабуевич', 'khgb@phystech.edu', '+79000000011', '3315100011');
INSERT INTO READER VALUES('Хамикова', 'Марина', 'Александровна', 'khma@phystech.edu', '+79000000012', '3315100012');
INSERT INTO READER VALUES('Швейкин', 'Денис', 'Александрович', 'shda@phystech.edu', '+79000000013', '3315100013');
INSERT INTO READER VALUES('Шелковникова', 'Ксения', 'Анатольевна', 'shka@phystech.edu', '+79000000014', '3315100014');
INSERT INTO READER VALUES('Абсалямов', 'Артур', 'Айдарович', 'aaa@phystech.edu', '+79000000015', '3315100015');
INSERT INTO READER VALUES('Ахметов', 'Кирилл', 'Николаевич', 'akn@phystech.edu', '+79000000016', '3315100016');
INSERT INTO READER VALUES('Дранов', 'Егор', 'Максимович', 'dem@phystech.edu', '+79000000017', '3315100017');
INSERT INTO READER VALUES('Исмагилов', 'Александр', 'Олегович', 'iao@phystech.edu', '+79000000018', '3315100018');
INSERT INTO READER VALUES('Кислинский', 'Данила', 'Сергеевич', 'kds@phystech.edu', '+79000000019', '3315100019');
INSERT INTO READER VALUES('Корольков', 'Егор', 'Романович', 'ker@phystech.edu', '+79000000020', '3315100020');
INSERT INTO READER VALUES('Лебедев', 'Константин', 'Дмитриевич', 'lkd@phystech.edu', '+79000000021', '3315100021');
INSERT INTO READER VALUES('Молодцов', 'Глеб', 'Львович', 'mgl@phystech.edu', '+79000000022', '3315100022');
INSERT INTO READER VALUES('Наумов', 'Андрей', 'Александрович', 'naa@phystech.edu', '+79000000023', '3315100023');
INSERT INTO READER VALUES('Павлов', 'Александр', 'Сергеевич', 'pas@phystech.edu', '+79000000024', '3315100024');
INSERT INTO READER VALUES('Станко', 'Сергей', 'Алексеевич', 'ssa@phystech.edu', '+79000000025', '3315100025');
INSERT INTO READER VALUES('Шестаков', 'Александр', 'Алексеевич', 'shaa@phystech.edu', '+79000000026', '3315100026');
INSERT INTO READER VALUES('Юков', 'Артём', 'Игоревич', 'yuai@phystech.edu', '+79000000027', '3315100027');

INSERT INTO DEAL VALUES(1, 1, '9-9-2010', '25-9-2020');
INSERT INTO DEAL VALUES(1, 2, '9-8-2010', '15-9-2020');
INSERT INTO DEAL VALUES(3, 1, '19-9-2020', '23-9-2020');
INSERT INTO DEAL VALUES(3, 5, '19-9-2020', '23-9-2020');
INSERT INTO DEAL VALUES(7, 11, '19-9-2019', NULL);
INSERT INTO DEAL VALUES(11, 9, '21-9-2020', '5-10-2020');
INSERT INTO DEAL VALUES(13, 4, '22-9-2020', '02-10-2020');
INSERT INTO DEAL VALUES(15, 8, '23-9-2020', '01-10-2020');
INSERT INTO DEAL VALUES(15, 15, '23-9-2020', '01-10-2020');
INSERT INTO DEAL VALUES(17, 14, '27-9-2020', '05-10-2020');

INSERT INTO TOPIC VALUES('Бизнес', NULL);
INSERT INTO TOPIC VALUES('Саморазвитие', NULL);
INSERT INTO TOPIC VALUES('Хобби', NULL);
INSERT INTO TOPIC VALUES('Художественная литература',NULL);
INSERT INTO TOPIC VALUES('Научпоп', NULL);
INSERT INTO TOPIC VALUES('Искусство', NULL);
INSERT INTO TOPIC VALUES('Крастота и здоровье', NULL);
INSERT INTO TOPIC VALUES('Макияж', 7);
INSERT INTO TOPIC VALUES('Биология', 5);
INSERT INTO TOPIC VALUES('Физика', 5);
INSERT INTO TOPIC VALUES('Ораторское искусство', 1)
INSERT INTO TOPIC VALUES('Психология', 5);

INSERT INTO PROFESSION VALUES('автор');
INSERT INTO PROFESSION VALUES('переводчик');

INSERT INTO CREATOR VALUES('Ричард Фейнман');
INSERT INTO CREATOR VALUES('С. Г. Тиходеев');
INSERT INTO CREATOR VALUES('О. Л. Тиходеева');
INSERT INTO CREATOR VALUES('Виктор Пелевин');
INSERT INTO CREATOR VALUES('Александр Панчин');
INSERT INTO CREATOR VALUES('Софья Багдасарова');
INSERT INTO CREATOR VALUES('Анна Рольская');
INSERT INTO CREATOR VALUES('Фил Найт');
INSERT INTO CREATOR VALUES('Йаэль Адлер');
INSERT INTO CREATOR VALUES('Том Хэнкс');
INSERT INTO CREATOR VALUES('Елена Крыгина');
INSERT INTO CREATOR VALUES('Ханья Янагихара');
INSERT INTO CREATOR VALUES('Крис Андерсон');
INSERT INTO CREATOR VALUES('Мария Ершова');
INSERT INTO CREATOR VALUES('Юваль Ной Харари');
INSERT INTO CREATOR VALUES('Дэниел Канеман');
INSERT INTO CREATOR VALUES('Хэл Элрод');
INSERT INTO CREATOR VALUES('Джей Мэг');
INSERT INTO CREATOR VALUES('Мари Кондо');
INSERT INTO CREATOR VALUES('Джо Диспенза');
INSERT INTO CREATOR VALUES('Джен Синсеро');
INSERT INTO CREATOR VALUES('Иоганн Генрих Борстель');

INSERT INTO BOOK_TOPIC VALUES(1, 10);
INSERT INTO BOOK_TOPIC VALUES(2, 4);
INSERT INTO BOOK_TOPIC VALUES(3, 6);
INSERT INTO BOOK_TOPIC VALUES(4, 6);
INSERT INTO BOOK_TOPIC VALUES(5, 6);
INSERT INTO BOOK_TOPIC VALUES(6, 1);
INSERT INTO BOOK_TOPIC VALUES(7, 9);
INSERT INTO BOOK_TOPIC VALUES(8, 4);
INSERT INTO BOOK_TOPIC VALUES(9, 8);
INSERT INTO BOOK_TOPIC VALUES(10, 2);
INSERT INTO BOOK_TOPIC VALUES(11, 11);
INSERT INTO BOOK_TOPIC VALUES(12, 9);
INSERT INTO BOOK_TOPIC VALUES(13, 9);
INSERT INTO BOOK_TOPIC VALUES(14, 12);
INSERT INTO BOOK_TOPIC VALUES(15, 2);
INSERT INTO BOOK_TOPIC VALUES(16, 2);
INSERT INTO BOOK_TOPIC VALUES(17, 3);
INSERT INTO BOOK_TOPIC VALUES(18, 12);
INSERT INTO BOOK_TOPIC VALUES(19, 2);
INSERT INTO BOOK_TOPIC VALUES(20, 9);


INSERT INTO BOOK_EDITORS VALUES(2, 1, 2);
INSERT INTO BOOK_EDITORS VALUES(2, 1, 3);
INSERT INTO BOOK_CREATORS VALUES(1, 1, 1);
INSERT INTO BOOK_CREATORS VALUES(1, 2, 4);
INSERT INTO BOOK_CREATORS VALUES(1, 3, 5);
INSERT INTO BOOK_CREATORS VALUES(1, 4, 6);
INSERT INTO BOOK_CREATORS VALUES(1, 5, 7);
INSERT INTO BOOK_CREATORS VALUES(1, 6, 8);
INSERT INTO BOOK_CREATORS VALUES(1, 7, 9);
INSERT INTO BOOK_CREATORS VALUES(1, 8, 10);
INSERT INTO BOOK_CREATORS VALUES(1, 9, 11);
INSERT INTO BOOK_CREATORS VALUES(1, 10, 12);
INSERT INTO BOOK_CREATORS VALUES(1, 11, 13);
INSERT INTO BOOK_CREATORS VALUES(1, 12, 14);
INSERT INTO BOOK_CREATORS VALUES(1, 13, 15);
INSERT INTO BOOK_CREATORS VALUES(1, 14, 16);
INSERT INTO BOOK_CREATORS VALUES(1, 15, 17);
INSERT INTO BOOK_CREATORS VALUES(1, 16, 18);
INSERT INTO BOOK_CREATORS VALUES(1, 17, 19);
INSERT INTO BOOK_CREATORS VALUES(1, 18, 20);
INSERT INTO BOOK_CREATORS VALUES(1, 19, 21);
INSERT INTO BOOK_CREATORS VALUES(1, 20, 22);